# Matrix Basics

In [1]:
import numpy as np

In [2]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
import torch

In [5]:
# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

# Create Matrices with Deafult Values

In [6]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [7]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [8]:
np.random.rand(2, 2)

array([[0.77073356, 0.18165188],
       [0.70549545, 0.31865375]])

In [9]:
torch.rand(2, 2)

tensor([[0.7723, 0.9444],
        [0.8438, 0.8849]])

# Seed for Reproducibility

In [10]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [72]:
  """np.random.seed(0) makes the random numbers predictable. If you set the np.random.seed(a_fixed_number) every time 
you call the numpy's other random function, , the result will be the same:

>>> import numpy as np
>>> np.random.seed(0) 
>>> perm = np.random.permutation(10) 
>>> print perm 
[2 8 4 9 1 6 7 3 0 5]
>>> np.random.seed(0) 
>>> print np.random.permutation(10) 
[2 8 4 9 1 6 7 3 0 5]
>>> np.random.seed(0) 
>>> print np.random.permutation(10) 
[2 8 4 9 1 6 7 3 0 5]
>>> np.random.seed(0) 
>>> print np.random.permutation(10) 
[2 8 4 9 1 6 7 3 0 5]
>>> np.random.seed(0) 
>>> print np.random.rand(4) 
[0.5488135  0.71518937 0.60276338 0.54488318]
>>> np.random.seed(0) 
>>> print np.random.rand(4) 
[0.5488135  0.71518937 0.60276338 0.54488318]
However, if you just call it once and use various random functions, the results will still be different:

>>> import numpy as np
>>> np.random.seed(0) 
>>> perm = np.random.permutation(10)
>>> print perm 
[2 8 4 9 1 6 7 3 0 5]
>>> np.random.seed(0) 
>>> print np.random.permutation(10)
[2 8 4 9 1 6 7 3 0 5]
>>> print np.random.permutation(10) 
[3 5 1 2 9 8 0 6 7 4]
>>> print np.random.permutation(10) 
[2 3 8 4 5 1 0 6 9 7]
>>> print np.random.rand(4) 
[0.64817187 0.36824154 0.95715516 0.14035078]
>>> print np.random.rand(4) 
[0.87008726 0.47360805 0.80091075 0.52047748]

source: stackoverflow  """

"np.random.seed(0) makes the random numbers predictable. If you set the np.random.seed(a_fixed_number) every time \nyou call the numpy's other random function, , the result will be the same:\n\n>>> import numpy as np\n>>> np.random.seed(0) \n>>> perm = np.random.permutation(10) \n>>> print perm \n[2 8 4 9 1 6 7 3 0 5]\n>>> np.random.seed(0) \n>>> print np.random.permutation(10) \n[2 8 4 9 1 6 7 3 0 5]\n>>> np.random.seed(0) \n>>> print np.random.permutation(10) \n[2 8 4 9 1 6 7 3 0 5]\n>>> np.random.seed(0) \n>>> print np.random.permutation(10) \n[2 8 4 9 1 6 7 3 0 5]\n>>> np.random.seed(0) \n>>> print np.random.rand(4) \n[0.5488135  0.71518937 0.60276338 0.54488318]\n>>> np.random.seed(0) \n>>> print np.random.rand(4) \n[0.5488135  0.71518937 0.60276338 0.54488318]\nHowever, if you just call it once and use various random functions, the results will still be different:\n\n>>> import numpy as np\n>>> np.random.seed(0) \n>>> perm = np.random.permutation(10)\n>>> print perm \n[2 8 4 9 1 

In [11]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [12]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [13]:
# No seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [14]:
# No seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [15]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [16]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [65]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [17]:
# Torch No Seed
torch.rand(2, 2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [18]:
# Torch No Seed
torch.rand(2, 2)

tensor([[0.4556, 0.6323],
        [0.3489, 0.4017]])

# Seed for GPU is different for now

In [19]:
torch.cuda.is_available()

False

In [66]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

# Torch to NumPy Bridge

In [21]:
# Numpy array
np_array = np.ones((2, 2))

In [22]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [23]:
print(type(np_array))

<class 'numpy.ndarray'>


In [24]:
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

In [25]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [26]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [67]:
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

# The conversation supports:
    
    1. double
    2. float
    3. int64, int32, uint8

In [28]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

In [29]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [30]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [31]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [32]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]])

In [33]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

   <img src="image/Array_type.png">

# Torch to NumPy

In [34]:
torch_tensor = torch.ones(2, 2)

In [35]:
type(torch_tensor)

torch.Tensor

In [36]:
torch_to_numpy = torch_tensor.numpy()

In [37]:
type(torch_to_numpy)

numpy.ndarray

# Tensors on GPU vs CPU

In [38]:
# CPU
tensor_cpu = torch.ones(2, 2)

In [39]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [40]:
# GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

# Basic Mathematical Tensor Operations
Resizing Tensor

In [41]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [42]:
print(a.size())

torch.Size([2, 2])


In [43]:
a.view(4)

tensor([1., 1., 1., 1.])

In [44]:
a.view(4).size()

torch.Size([4])

# Element- Wise Addition

In [45]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [46]:
b = torch.ones(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [47]:
# Element-wise addition
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [48]:
# Element-wise addition
c = torch.add(a, b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [49]:
# In-place addition
print('Old c tensor')
print(c)

c.add_(a)

print('-'*60)
print('New c tensor')
print(c)

Old c tensor
tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
New c tensor
tensor([[3., 3.],
        [3., 3.]])


In [73]:
 """ Adding two tensors
import torch

>>> x = torch.rand(1)
>>> x

 0.2362
[torch.FloatTensor of size 1]


>>> y = torch.rand(1)
>>> y

 0.7030
[torch.FloatTensor of size 1]
Normal addition
# Addition of two tensors creates a new tensor.
>>> x + y

 0.9392
[torch.FloatTensor of size 1]


# The value of x is unchanged.
>>> x

 0.2362
[torch.FloatTensor of size 1]
In-place addition
# An in-place addition modifies one of the tensors itself, here the value of x.
>>> x.add_(y)

 0.9392
[torch.FloatTensor of size 1]


>>> x

 0.9392
[torch.FloatTensor of size 1]  """

' Adding two tensors\nimport torch\n\n>>> x = torch.rand(1)\n>>> x\n\n0.2362\n[torch.FloatTensor of size 1]\n\n\n>>> y = torch.rand(1)\n>>> y\n\n0.7030\n[torch.FloatTensor of size 1]\nNormal addition\n# Addition of two tensors creates a new tensor.\n>>> x + y\n\n0.9392\n[torch.FloatTensor of size 1]\n\n\n# The value of x is unchanged.\n>>> x\n\n0.2362\n[torch.FloatTensor of size 1]\nIn-place addition\n# An in-place addition modifies one of the tensors itself, here the value of x.\n>>> x.add_(y)\n\n0.9392\n[torch.FloatTensor of size 1]\n\n\n>>> x\n\n0.9392\n[torch.FloatTensor of size 1]  '

# Element- Wise Subtraction

In [50]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [51]:
a - b

tensor([[0., 0.],
        [0., 0.]])

In [52]:
# Not in-place
print(a.sub(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [53]:
# Inplace
print(a.sub_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


# Element- Wise Multiplication

In [54]:
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [55]:
a * b

tensor([[0., 0.],
        [0., 0.]])

In [56]:
# Not in-place
print(torch.mul(a, b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [57]:
# In-place
print(a.mul_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


# Element- Wise Division

In [58]:
a = torch.ones(2, 2)
b = torch.zeros(2, 2)

In [59]:
b / a

tensor([[0., 0.],
        [0., 0.]])

In [60]:
torch.div(b, a)

tensor([[0., 0.],
        [0., 0.]])

In [61]:
# Inplace
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

# Tensor Mean
1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 +10 = 55

mean = 55/10 = 5.5

In [62]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [63]:
a.mean(dim=0)

tensor(5.5000)

In [64]:
a.mean(dim=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [69]:
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [70]:
a.size()

torch.Size([2, 10])

In [71]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

# Tensor Standard Deviation

In [ ]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)